# .github/workflows/scheduled-builds.yml
name: Test Website
on:
  push:
    branches:
      - master
  schedule:
    # Runs “At 00:00 on Sunday.”
    - cron: '0 0 * * SUN'
jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: Test farukcan.net
        # Hit the webhook endpoint to rebuild  from the "main" branch
        run: wget -p https://farukcan.net
