# .github/workflows/scheduled-builds.yml
name: Test farukcan.net

on:
  schedule:
    # Runs “At 00:00 on Sunday.”
    - cron: '0 0 * * SUN'
jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        # Hit the webhook endpoint to rebuild  from the "main" branch
        run: curl -X GET https://farukcan.net
