# .github/workflows/scheduled-builds.yml
name: Test Website
on:
  push:
    branches:
      - master
  schedule:
    # Runs “At 00:00” - crontab.guru
    - cron: '0 0 * * *'
jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: Test farukcan.net
        run: wget -p https://farukcan.net
      - name: Test farukcan.dev
        run: wget -p https://farukcan.dev
