# .github/workflows/scheduled-builds.yml
name: Test Websites
on:
  push:
    branches:
      - master
  schedule:
    # Runs “At 00:00” - crontab.guru
    - cron: '0 0 * * *'
jobs:
  build:
    name: Testing websites
    runs-on: ubuntu-latest
    steps:
      - name: Test farukcan.net
        run: wget -p https://farukcan.net
      - name: Test farukcan.dev
        run: wget -p https://farukcan.dev
      - name: Test errorsample56754654.dev
        run: wget -p https://errorsample56754654.dev
      - name: Send Notification
        if: failure()
        run:  curl -d '{"body":"body test", "title":"title test"}' -H 'Content-Type: application/json' ${{ secrets.APPRISE_URL }}
